"use strict";
var age1 = 10;
var name1 = "Hello Brother";
var isMale = true;
console.log(typeof age1);
console.log(typeof name1);
console.log(typeof isMale);
let myvar;
myvar = 10;
console.log(typeof myvar);
myvar = "Ali";
console.log(typeof myvar);
myvar = null;
console.log(typeof myvar);
